### ISSUE TITLE
Let's Stop 🛑 passing props

### ISSUE THREAD

**Issue by ghost** [cassidoo/solid-pi-guesser#1]
One of the most Awesome things that we can find in Solid.js is global State management. In Solid.js, createSignal is not locked up in a component, we can move to it's own file or take out of a component & import it to our components, then  Solid.js will keep track of Signals & update the UI accordingly. Also Solid.js has createMutable, which works like mobx observables.
Just see my port of your pi guessing App https://pi-guesser.pages.dev/.

Some videos that can help you to learn Solid.js more are:
https://m.youtube.com/watch?v=ZZ-a7B761Ds
https://m.youtube.com/watch?v=Xw9XMNn2k0o
https://m.youtube.com/watch?v=LZc2hSghezM
https://m.youtube.com/watch?v=cFasysKU7vk

**Comment by cassidoo** [comment]
Thanks for the details! So basically you are doing the same state logic, just separate from the component logic?

**Comment by ghost** [comment]
What I just did was I build it with global State. As you can realize it's simple, don't need to pass props to components, just import the global State & use it. Also  I am using the Coolest Solid App Router & built-in solid.js components like Show, Suspense. One thing that I need to mention is that I am using Solid Start (https://github.com/solidjs/solid-start) which is a Solid-js full stack framework (by disabling ssr in vite.config.ts).

**Comment by ghost** [comment]
Hey Cassidoo, I might be able to fix the Input Problem. What I did was I use a createMemo to generate the Last Character of the currentGuess & Pass to checkDigits without needing to clear the currentGuess.

![Screenshot_20220315-093524_GitHub~2.jpg](https://user-images.githubusercontent.com/96905008/158380386-eb1f7d1b-7ed2-4c7e-852d-57829c0b5e5a.jpg)

![Screenshot_20220315-094503_Chrome.jpg](https://user-images.githubusercontent.com/96905008/158380537-7674067f-341b-427c-84d2-987561977ac2.jpg)

Please see these article:  https://bobbyhadz.com/blog/javascript-get-last-character-of-string
